# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675c54db8f402db142e93751c6dde5f0d368406482453cdd84da8792ea45125f18f91f53c03358205c9274026681919b3860e583e8b81583d0ac1b18a281c088

test:
  secret_key_base: 76656099d97782193d75b9fa41e48a4eec743391002607db3aef37e02d627cd8d6f52d24bfb3e859866b572f5a4080dc77ed4fd83e450d17c79efeb3c4b8e616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
